"""Fix models

Revision ID: 486bd4d8a4f3
Revises: 87985485b14f
Create Date: 2025-06-28 08:59:01.947639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486bd4d8a4f3'
down_revision = '87985485b14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_mood', type_='foreignkey')
        batch_op.drop_column('mood_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_post_mood', 'moods', ['mood_id'], ['id'])

    # ### end Alembic commands ###
