"""Add mood_id to Post

Revision ID: 87985485b14f
Revises: a7ff9a66867b
Create Date: 2025-06-28 03:11:56.318893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87985485b14f'
down_revision = 'a7ff9a66867b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_post_mood', 'moods', ['mood_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mood_id')

    # ### end Alembic commands ###
