"""Add Mood model

Revision ID: febfec03302e
Revises: d3f9dd12a104
Create Date: 2025-07-07 21:35:30.052324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febfec03302e'
down_revision = 'd3f9dd12a104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('note')
        batch_op.drop_column('mood')

    # ### end Alembic commands ###
